# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 183c24fdcdcdfffadf5c57951ee1aa3589088e73a3474363029a8f4bccd5ce3fcfddf99f2dbf2ff0fc6567d60c975921b11da8c3f6000fe22c9fbed172fc25c4

test:
  secret_key_base: dbb5fa5928a011a3310112b36f39e6ae439ffe635460aaec5e9ac79840c63b1c9378d58b30216c8848b5960a51857e9e147b2c31c3828e1ba9fd8f32f04f48c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
